name: Run Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUSKY_GIT_DIR: ${{ github.workspace }}/.git

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Latest LTS version as of now

    - name: Install Husky
      run: npx husky install --ci
      working-directory: ${{ github.workspace }}

    - name: Install dependencies
      run: |
        echo "HUSKY_GIT_DIR=$HUSKY_GIT_DIR"
        npm install --legacy-peer-deps
      working-directory: ${{ github.workspace }}/javascript

    - name: Run tests
      run: npm test
      working-directory: ${{ github.workspace }}/javascript